###

@host = 172.16.60.89
@port = 7480
@access_key = LFFBEITQZ9KFQY4LF4EU
@signature = ewRYPDqwI++sOkXDCW7ylsZKBHM=
@now_date = Fri, 20 Mar 2020 06:00:00 +0000


// 获取请求者使用状态
GET /?usage HTTP/1.1
Host: {{host}}:{{port}}
Date: {{now_date}}
Authorization: AWS {{access_key}}:{{signature}}